### ISSUE TITLE
Better "preprocessors" configuration

### ISSUE THREAD

**Issue by hbredin** [pyannote/pyannote-pipeline#8]
For now,  `pyannote.pipeline.Experiment` only supports `database.yml`-like or template preprocessors:

```yaml
preprocessors:
  new_key_1: /path/to/my/database.yml
  new_key_2: /path/to/my/{uri}.wav 
```

Would be nice if one could also do something like:
```yaml
preprocessors:
  new_key:
    name: package.module.ClassName
    params:
      param1: value1
      param2: value2
```

It would first instantiate ClassName with the given params
ClassName instances should be callable expecting `current_file` as unique argument.
